### ISSUE TITLE
Adding car thumbnails

### ISSUE THREAD

**Issue by bnowakow** [ddm999/gt7info#1]
First of all - great work on creating this dashboard and make .json public - appreciate it!

Septomor used your data to create https://mcbeej.github.io which adds car thumbnails to most of cars. Would you be interested to use his pictures to you dashboard?

**Comment by ddm999** [comment]
👀
I think for me it's something I'd wait for game data to be accessible before doing.
After all, the actual screenshots used in both dealerships in-game will likely just be stored as plain images in the game files.

I'd imagine their images used on that site come from game screenshots of their own car collection, but that means:
- you're stuck with that background
- cars they haven't collected (such as the Alfa Romeo 155 DTM) are the blank shadow thumbnails
- the text is baked in

Always happy to see my data being used though 👍

**Comment by bnowakow** [comment]
Yup, it's game screenshots.
