### ISSUE TITLE
Road Atlanta missing

### ISSUE THREAD

**Issue by Bornhall** [ddm999/gt7info#3]
Just noted that **Road Atlanta** is missing in course.csv.

**Comment by ddm999** [comment]
whoops! will fix ASAP, thanks for letting me know 😅

**Comment by ddm999** [comment]
Fixed:
I also corrected Grand Valley Short data (i counted 11 corners, GT says 10 corners)
and track logos have been added for Grand Valley & Road Atlanta

**Comment by Bornhall** [comment]
Come to think of it when you mention track logos, are there any available track maps in SVG or the like from within the game? I assume there are PNG track maps if one is so inclined to find them from PD's web page, but I was thinking more along the lines of scalable versions.

**Comment by ddm999** [comment]
If I remember correctly, they no longer use an image format at all for the maps in-game.
They're only stored in a proprietary format as a 3D spline, because they're used for the in-game 3D track map.

So unfortunately not really usable (we don't know the format). :(
