### ISSUE TITLE
Add "Three Legendary Cars" info to Legend cars dealership

### ISSUE THREAD

**Issue by A1rPun** [ddm999/gt7info#4]
Hey, great work on this project.

I believe many of us are using this site to check when one of the 3 legendary cars appear in the Legend cars dealership. Can this info be added and displayed for:

Car
-- |
Ford Mark IV Race Car '67
Jaguar XJ13 '66
Ferrari 330 P4 '67

I can make a PR if you want :)

**Comment by ddm999** [comment]
Good idea, not sure why I didn't think of it myself :)
I'll do this myself now, shouldn't take too long

**Comment by ddm999** [comment]
All done & I've cleaned up how the LCD displays a bit too.

Here's an example of how it looks:
![image](https://user-images.githubusercontent.com/8524741/235823506-4bab85b3-0476-496c-9959-c6d109c6d8d0.png)

**Comment by A1rPun** [comment]
Thanks for the implementation, looks great! Looking forward to see it live :smile:
