### ISSUE TITLE
Available For n More Days is 1 Day too much

### ISSUE THREAD

**Issue by tmuthmann** [ddm999/gt7info#6]
Hi,
first of all thx for this great Project.

One minor issue though:
The actual Alfa 8C shows Limited Stock for 1 more Day today, which is correct.
Yesterday it was Available For 3 More Days.
So you need to substract 2 from the CSV value daysremaining for this display type.
daysremaining is the time a car is displayed, including today, and you need to refactor the out of stock day in.
As said before, Limited Stock and Out of Stock Display is correct.

**Comment by ddm999** [comment]
I'll verify this, but have you noticed this happening any other times?
All the dealership data gets messed around with when a GT7 update comes out & that might be the cause of this issue (and that's unfixable, it's an issue on Polyphony's end).

**Comment by tmuthmann** [comment]
I think daysremaining means: Days on Display, including today:
See todays CSV:
normal 	5	Ferrari 365
soldout 	1	Ferrari 330
limited 	2	Alfa 8C
interpreting daysremaining:
1 = 1 more Day on Display, already Sold out
2 = 2 more Days on Display, second Day Limited
3 = 3 more Days on Display, first Day Limited
4 = 4 more Days on Display, should be: Available for 2 More Days
5 = 5 more Days on Display, should be: Available for 3 More Days
As you can see, the Ferrari 365 shows 4 More Days right now, which is wrong.
Substract 1 for Today and 1 for Sold out from daysremaining.

BTW:
How do you get those values in the CSVs?
I can only imagine by doing packet sniffing.

**Comment by ddm999** [comment]
Verified & now fixed.
