### ISSUE TITLE
legend bug as of 12sep

### ISSUE THREAD

**Issue by mattlenglish** [ddm999/gt7info#7]
Hi ddm-

The first car in the legend list is missing - data file has 10 instead of the proper 11.  First car should be 3509, the '73 911, starting on 12sep.

Best,
Matt

**Comment by mattlenglish** [comment]
![IMG_2379](https://github.com/ddm999/gt7info/assets/202872/03fb390c-c1c5-46f8-9b69-779555ffa2f3)
![IMG_2381](https://github.com/ddm999/gt7info/assets/202872/f187289e-36fa-4ac1-91e0-0c8f9f87ed88)

**Comment by ddm999** [comment]
Yeah, I'm aware it's happening.
It seems to be that PD have changed how the "Special Picks" work which is causing an issue with how I add the data.
I'm looking into tracking down where it's gone to so they'll appear in the data & on the site again.

**Comment by ddm999** [comment]
Okay, I never actually touched anything but it appears it came back to the site & data on the 16th of September: PD must've reverted their change.

I'm going to close this as it seems to have just resolved itself.
